In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.5'

### 1- array

#### 1_D array

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


#### 2_D array

In [6]:
two_d = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

In [7]:
print(two_d)

[[1 2 3 4 5]
 [1 2 3 4 5]]


#### 3_D array

In [8]:
three_d = np.array([[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]],[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]])

In [9]:
print(three_d)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [10]:
nd_array = np.array([1, 2, 3, 5, 6], ndmin = 5)
print(nd_array)

[[[[[1 2 3 5 6]]]]]


In [11]:
arr_comp = np.array([[1, 2,],[3, 4]], dtype = complex)
print(arr_comp)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


### 2-ndim

In [12]:
print(arr.ndim)
print(two_d.ndim)
print(three_d.ndim)
print(nd_array.ndim)

1
2
3
5


### 3-Shape

In [13]:
print(arr.shape)
print(two_d.shape)
print(three_d.shape)
print(nd_array.shape)

(5,)
(2, 5)
(2, 2, 5)
(1, 1, 1, 1, 5)


### 4-dtype

In [14]:
print(arr.dtype)
print(two_d.dtype)
print(three_d.dtype)
print(nd_array.dtype)
print(arr_comp.dtype)

int32
int32
int32
int32
complex128


In [15]:
type(arr)
type(arr_comp)

numpy.ndarray

### 5-itemsize

In [16]:
print(arr.itemsize)
print(two_d.itemsize)
print(three_d.itemsize)
print(nd_array.itemsize)
print(arr_comp.itemsize)

4
4
4
4
16


### 6-Zeros

In [17]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [18]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 7-zeros_like

In [19]:
zeros= [[1,2, 3, 3, 3, 4],[1, 2, 3, 3, 3, 4]]
print(np.zeros_like(zeros))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### 8-ones

In [20]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [21]:
ones_arr = np.ones((3, 3, 2), dtype=np.int16)
print(ones_arr)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


### 9-ones_like

In [22]:
ones= [[1,2, 3, 3, 3, 4],[1, 2, 3, 3, 3, 4]]
print(np.ones_like(ones))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


### 10-empty

In [23]:
uninit = np.empty((2, 3))
print(uninit)

[[2.12199579e-314 2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314 2.12199579e-314]]


### 11-empty_like

In [24]:
empt =[[1,2, 3, 3, 3, 4],[1, 2, 3, 3, 3, 4]]
empt_like = np.empty_like(empt)
print(empt_like)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


### 12-arange

In [25]:
print(np.arange(0, 10, 0.3))

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8 5.1
 5.4 5.7 6.  6.3 6.6 6.9 7.2 7.5 7.8 8.1 8.4 8.7 9.  9.3 9.6 9.9]


In [26]:
print(np.arange(1, 11, 2))

[1 3 5 7 9]


### 13-reshape

In [27]:
ar = np.arange(16)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [28]:
ar = np.arange(12).reshape(3,4)
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
ar1 = np.arange(48).reshape(2, 2 ,3 ,4)
print(ar1)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


### 14-full

In [30]:
ful = np.full((3, 3), 10.2)
print(ful)

[[10.2 10.2 10.2]
 [10.2 10.2 10.2]
 [10.2 10.2 10.2]]


In [31]:
ful1 = np.full((3, 3), np.inf)
print(ful1)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [32]:
ful2 = np.full((3, 3, 3), 55, dtype = int)
print(ful2)

[[[55 55 55]
  [55 55 55]
  [55 55 55]]

 [[55 55 55]
  [55 55 55]
  [55 55 55]]

 [[55 55 55]
  [55 55 55]
  [55 55 55]]]


### 15-full_like

In [33]:
print(np.full_like(ful2, 33, dtype = float))

[[[33. 33. 33.]
  [33. 33. 33.]
  [33. 33. 33.]]

 [[33. 33. 33.]
  [33. 33. 33.]
  [33. 33. 33.]]

 [[33. 33. 33.]
  [33. 33. 33.]
  [33. 33. 33.]]]


### 16-astype

In [34]:
print(ful)

[[10.2 10.2 10.2]
 [10.2 10.2 10.2]
 [10.2 10.2 10.2]]


In [35]:
print(ful.astype(np.int32))

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### 17-arithmatics

In [36]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)
arr2 = np.arange(2 , 20, 2).reshape(3, 3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [37]:
print("Addition  :", arr1 + 5 )
print("Multiplication :", arr1 * 4)
print("Square :", arr1**2)
print("Subtraction :", arr1 - arr1)
print("Reciprocal",1 / arr1 )
print("Comparision :",arr1 < arr2 )

Addition  : [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Multiplication : [[ 4  8 12]
 [16 20 24]
 [28 32 36]]
Square : [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Subtraction : [[0 0 0]
 [0 0 0]
 [0 0 0]]
Reciprocal [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]
Comparision : [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 18-eye

In [38]:
# It creates digonally 1 element
eyed = np.eye(2, 2)
print(eyed)

[[1. 0.]
 [0. 1.]]


In [39]:
eyed1 = np.eye(3, 3)
print(eyed1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
eyed2 = np.eye(4, 4)
print(eyed2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
eyed3 = np.eye(3, 4)
print(eyed3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 19-identitiy

In [42]:
# creates squared digonals with 1
id = np.identity(2)
print(id)

[[1. 0.]
 [0. 1.]]


In [43]:
id1 = np.identity(3)
print(id1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 20-linespace

In [44]:
lnsp = np.linspace(1, 2, 10)
print(lnsp)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [45]:
import sys
np.set_printoptions(threshold = sys.maxsize)

In [46]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

### 21-product

In [47]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A * B  

array([[2, 0],
       [0, 4]])

In [48]:
A @ B   

array([[5, 4],
       [3, 4]])

In [49]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

### 22-sum

In [50]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
print(arr1.sum())

45


### 23-min

In [52]:
print(arr1.min())

1


### 24-max

In [53]:
print(arr1.max())

9


### 25-cumulative sum

In [54]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
print(b.cumsum(axis=0))

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


### 26-exp

In [56]:
print(np.exp(b))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


### 27-sqrt

In [57]:
print(np.sqrt(b))

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


In [58]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 28-add

In [60]:
np.add(a, b)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

### 29-all

In [61]:
np.all(a)

False

In [62]:
np.all(arr1)

True

### 30-any

In [63]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
a0  = np.any(arr1, axis = 1)
print(a0)

[ True  True  True]


In [65]:
a1 = np.any(a, axis = 0)
print(a1)

[ True  True  True  True]


### 31-apply along axis

In [72]:
ar1 = np.array([[8,1,7], [4,3,9], [5,2,6]])
ar1

array([[8, 1, 7],
       [4, 3, 9],
       [5, 2, 6]])

In [71]:
np.apply_along_axis(sorted, 1, b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 32-argmax

In [73]:
a = np.arange(6).reshape(2,3) + 10  
a

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
np.argmax(a)    #returns indeces of max value in an axis

5

### 33-argmin

In [81]:
np.argmin(a)    #returns indeces of minimum value in an axis

0

### 34-argsort

In [82]:
ar1

array([[8, 1, 7],
       [4, 3, 9],
       [5, 2, 6]])

In [86]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [87]:
print(np.argsort(ar1))   #Returns the indices that would sort an array.

[[1 2 0]
 [1 0 2]
 [1 0 2]]


### 35-average

In [88]:
data = np.arange(1, 5)
data

array([1, 2, 3, 4])

In [91]:
np.average(data)  # Compute the weighted average along the specified axis.

2.5

In [95]:
np.average(np.arange(1, 11), weights=np.arange(10, 0, -1))

4.0

### 36-bincount

In [99]:
#Count number of occurrences of each value in array of non-negative ints.

In [101]:
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1], dtype=int64)

In [102]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int64)

### 37-ceil

In [103]:
# Return the ceiling of the input, element-wise.

In [104]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

### 38-floor

In [105]:
# Return the floor of the input, element-wise.

In [106]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

### 39-inner

In [107]:
# Inner product of two arrays.

In [108]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [110]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
np.inner(a, b)

array([[ 14,  38,  62],
       [ 86, 110, 134]])

### 40-outer

In [111]:
# Compute the outer product of two vectors.

In [113]:
x = np.array(['a', 'b', 'c'], dtype=object)
ot = np.outer(x, [1, 2, 3])
print(ot)

[['a' 'aa' 'aaa']
 ['b' 'bb' 'bbb']
 ['c' 'cc' 'ccc']]


### 41-mean

In [114]:
# Compute the arithmetic mean along the specified axis.

In [115]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [116]:
np.mean(a, axis = 0)

array([2., 3.])

In [117]:
np.mean(a, axis = 1)

array([1.5, 3.5])

### 42-median

In [118]:
# Compute the median along the specified axis.

In [119]:
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [120]:
np.median(a)

3.5

In [121]:
np.median(a, axis=0)

array([6.5, 4.5, 2.5])

In [122]:
np.median(a, axis=1)

array([7., 2.])

### 43-clip

In [123]:
# Clip (limit) the values in an array.

In [124]:
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [125]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 44-invert

In [134]:
# Compute bit-wise inversion, or bit-wise NOT, element-wise.

In [139]:
a = np.array(13, dtype=np.uint8)
print(a)

13


In [137]:
x = np.invert(a)
x

242

In [133]:
np.binary_repr(x, width=8)

'11110010'

### 45-shallo copy

In [140]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [141]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
c = a.view()
c
c is a

False

In [150]:
c.flags.owndata

False

In [151]:
c.shape

(3, 4)

In [153]:
c = c.reshape((2, 6)) # shape of view cannot be changed

### 46-deep copy

In [159]:
d = a.copy()

In [160]:
d
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [161]:
d.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])